version: '2'
services:
    proyservice1-app:
        image: proyservice1
        external_links:
            - proyservice1-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/proyservice1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    proyservice1-mysql:
        extends:
            file: mysql.yml
            service: proyservice1-mysql
